### ISSUE TITLE
error: package.el is not yet initialized!

### ISSUE THREAD

**Issue by shxiangyan** [EvanMeek/.emacs.d#1]
请问当我克隆了.emacs.d之后,运行的时候出现这样的问题该如何解决?
Warning (initialization): An error occurred while loading ‘/home/user/.emacs.d/init.el’:

error: package.el is not yet initialized!

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

**Comment by EvanMeek** [comment]
# 1 emacs -q 下手动加载

使用`emacs -q`启动emacs，然后找到我配置的etc/config/init-package.el，逐行eval(C-x C-e)配置，看具体是哪行出错了，得到的错误看看能不能解决，不能的话将报错信息发到这里来。

**Comment by EvanMeek** [comment]
Fixed

**Comment by shxiangyan** [comment]
谢谢大佬

Evan <notifications@github.com> 于2020年5月13日周三 下午5:10写道：
