### ISSUE TITLE
安装最后一步的问题

### ISSUE THREAD

**Issue by heisaari** [EvanMeek/.emacs.d#1]
git submodule --init --recursive  这句执行后：
返回
<pre>用法：git submodule [--quiet] [--cached]
   or: git submodule [--quiet] add [-b &lt;branch&gt;] [-f|--force] [--name &lt;name&gt;] [--reference &lt;repository&gt;] [--] &lt;repository&gt; [&lt;path&gt;]
   or: git submodule [--quiet] status [--cached] [--recursive] [--] [&lt;path&gt;...]
   or: git submodule [--quiet] init [--] [&lt;path&gt;...]
   or: git submodule [--quiet] deinit [-f|--force] (--all| [--] &lt;path&gt;...)
   or: git submodule [--quiet] update [--init] [--remote] [-N|--no-fetch] [-f|--force] [--checkout|--merge|--rebase] [--[no-]recommend-shallow] [--reference &lt;repository&gt;] [--recursive] [--] [&lt;path&gt;...]
   or: git submodule [--quiet] set-branch (--default|--branch &lt;branch&gt;) [--] &lt;path&gt;
   or: git submodule [--quiet] set-url [--] &lt;path&gt; &lt;newurl&gt;
   or: git submodule [--quiet] summary [--cached|--files] [--summary-limit &lt;n&gt;] [commit] [--] [&lt;path&gt;...]
   or: git submodule [--quiet] foreach [--recursive] &lt;command&gt;
   or: git submodule [--quiet] sync [--recursive] [--] [&lt;path&gt;...]
   or: git submodule [--quiet] absorbgitdirs [--] [&lt;path&gt;...]</pre>

**Comment by EvanMeek** [comment]
git submodule update --init -recursive

**Comment by heisaari** [comment]
> 

换用此命令返回同上，谢谢

**Comment by EvanMeek** [comment]
> > 
> 
> 换用此命令返回同上，谢谢
git submodule update --init --recursive

**Comment by heisaari** [comment]
git@github.com: Permission denied (publickey).
fatal: 无法读取远程仓库。

请确认您有正确的访问权限并且仓库存在。
fatal: 无法克隆 'git@github.com:EvanMeek/shengci.el.git' 到子模组路径 '/home/sisu/.emacs.d/site-lisp/pkg/shengci.el'
第二次尝试克隆 'site-lisp/pkg/shengci.el' 失败，退出

**Comment by heisaari** [comment]
git@github.com: Permission denied (publickey).
fatal: 无法读取远程仓库。

请确认您有正确的访问权限并且仓库存在。
fatal: 无法克隆 'git@github.com:EvanMeek/shengci.el.git' 到子模组路径 '/home/user/.emacs.d/site-lisp/pkg/shengci.el'
第二次尝试克隆 'site-lisp/pkg/shengci.el' 失败，退出

**Comment by EvanMeek** [comment]
git submodule update --init --recursive



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月18日(周一) 晚上10:15
抄送: ***@***.***&gt;;
主题: [EvanMeek/.emacs.d] 安装最后一步的问题 (Issue #1)




 
git submodule --init --recursive  这句执行后：
 返回
 用法：git submodule [--quiet] [--cached]    or: git submodule [--quiet] add [-b <branch&gt;] [-f|--force] [--name <name&gt;] [--reference <repository&gt;] [--] <repository&gt; [<path&gt;]    or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path&gt;...]    or: git submodule [--quiet] init [--] [<path&gt;...]    or: git submodule [--quiet] deinit [-f|--force] (--all| [--] <path&gt;...)    or: git submodule [--quiet] update [--init] [--remote] [-N|--no-fetch] [-f|--force] [--checkout|--merge|--rebase] [--[no-]recommend-shallow] [--reference <repository&gt;] [--recursive] [--] [<path&gt;...]    or: git submodule [--quiet] set-branch (--default|--branch <branch&gt;) [--] <path&gt;    or: git submodule [--quiet] set-url [--] <path&gt; <newurl&gt;    or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n&gt;] [commit] [--] [<path&gt;...]    or: git submodule [--quiet] foreach [--recursive] <command&gt;    or: git submodule [--quiet] sync [--recursive] [--] [<path&gt;...]    or: git submodule [--quiet] absorbgitdirs [--] [<path&gt;...]
