### ISSUE TITLE
请问你是怎么在eaf-browser中使用meow的

### ISSUE THREAD

**Issue by ShaMaTeTuanZhang** [EvanMeek/.emacs.d#2]
eaf项目会覆盖`SPC`的meow-keypad,目前不知道怎么解决
仿照eaf-evil写一个,但接口又有一些不一样

**Comment by EvanMeek** [comment]
(eaf-bind-key meow-keypad "SPC" eaf-browser-keybinding)
(eaf-bind-key eaf-py-proxy-insert_or_scroll_up_page "M-SPC" eaf-browser-keybinding)

**Comment by ShaMaTeTuanZhang** [comment]
感谢,但我在eaf浏览器文本框输入时 `SPC` 也会判定为空格

**Comment by EvanMeek** [comment]
我现在也不清楚要如何解决

**Comment by spcmxxd** [comment]
@EvanMeek 作者您好，我现在也遇到了同样的问题。

设置 `(eaf-bind-key meow-keypad "SPC" eaf-browser-keybinding)` 之后，可以在 eaf-browser 中与外部保持同样的逻辑，即用 SPC 唤醒 meow-keypad

但是这样设置之后无法在 google.com 输入文本的时候键入空格。请问作者现在有解决该问题的方法了吗？感谢
