### ISSUE TITLE
emacs配置搬运后不能使用

### ISSUE THREAD

**Issue by 913650629** [EvanMeek/.emacs.d#3]
直接打开emacs文件后是以下效果：
![image](https://user-images.githubusercontent.com/66675245/110901573-7986fc80-833f-11eb-8b7f-fd5610dddbd6.png)
经过一段时间排除后，发现问题在init-basic中，注释init-basic后，能正常显示页面
![image](https://user-images.githubusercontent.com/66675245/110901846-e4d0ce80-833f-11eb-8687-44b1897d21a4.png)
查看init-basic文件后，以为是rime的问题，使用命令yay -S fcitx5-rime 安装rime后，没有生成~/.local/share/fcitx/rime，重新创建了一个rime文件夹后，还是不行，目前没找到解决方法。

**Comment by EvanMeek** [comment]
> 直接打开emacs文件后是以下效果：
> ![image](https://user-images.githubusercontent.com/66675245/110901573-7986fc80-833f-11eb-8b7f-fd5610dddbd6.png)
> 经过一段时间排除后，发现问题在init-basic中，注释init-basic后，能正常显示页面
> ![image](https://user-images.githubusercontent.com/66675245/110901846-e4d0ce80-833f-11eb-8687-44b1897d21a4.png)
> 查看init-basic文件后，以为是rime的问题，使用命令yay -S fcitx5-rime 安装rime后，没有生成~/.local/share/fcitx/rime，重新创建了一个rime文件夹后，还是不行，目前没找到解决方法。
> 

解决了么，是QQ上的好友么

**Comment by 913650629** [comment]
是的，谢谢群主啦！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EvanMeek/.emacs.d"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月15日(星期一) 晚上7:31
收件人:&nbsp;"EvanMeek/.emacs.d"<&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [EvanMeek/.emacs.d] emacs配置搬运后不能使用 (#3)





  
直接打开emacs文件后是以下效果：
 
 经过一段时间排除后，发现问题在init-basic中，注释init-basic后，能正常显示页面
 
 查看init-basic文件后，以为是rime的问题，使用命令yay -S fcitx5-rime 安装rime后，没有生成~/.local/share/fcitx/rime，重新创建了一个rime文件夹后，还是不行，目前没找到解决方法。
  
解决了么，是QQ上的好友么
